### ISSUE TITLE
Can not install app on the device

### ISSUE THREAD

**Issue by sakibk** [TheraForge/OTFMagicBox#1]
I am not able to install app on the device. 
I got following errors:

> No account for team "2ACH4UKQKX". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.

> No profiles for 'org.theraforge.magicbox.ios' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'org.theraforge.magicbox.ios'.

How can I solve this one, or I am not able to run it on device at all?

**Comment by marco-theraforge** [comment]
Thanks for pointing this out, Sakib.
We need to explain this part of the process in the documentation. A new team and bundle ID need to be specified in Xcode. We'll add some screenshots and instructions on how to proceed.
Good catch!

**Comment by marco-theraforge** [comment]
We have updated the documentation in release 1.02 to include the registration steps and Xcode setup process to add a physical device to the list of supported devices to run the app on.
Closing the comment.
