### ISSUE TITLE
Entitlements file was modified during the build, which is not supported

### ISSUE THREAD

**Issue by sakibk** [TheraForge/OTFMagicBox#2]
After installing cocoapods and trying to run application, I got following issue:

> error: Entitlements file "OTFMagicBox.entitlements" was modified during the build, which is not supported. You can disable this error by setting 'CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION' to 'YES', however this may cause the built product's code signature or provisioning profile to contain incorrect entitlements. (in target 'OTFMagicBox' from project 'OTFMagicBox')

How to proceed?

**Comment by marco-theraforge** [comment]
Hi Sakib,

this is a known issue that can sometimes happen. The recommended fix is to run:

Product > Clean Build Folder

https://stackoverflow.com/questions/55456335/entitlements-file-was-modified-during-the-build-which-is-not-supported

We will update the documentation to alert on this possibility and point out the recommended fix.

**Comment by marco-theraforge** [comment]
We have improved the documentation in release 1.0.2. Hopefully that provides plenty of information to help in these kinds of situations.
Closing the issue.
Please feel free to reopen it if further improvements are required.
