### ISSUE TITLE
Installation of Cocoapods not working

### ISSUE THREAD

**Issue by sakibk** [TheraForge/OTFMagicBox#3]
Since Cocoapods are not released yet, the guidelines from readme are not working at initial installation. When running command `pod install` inside of terminal we got error that since they are not released, we need to specify version we want to install.
How to do this one?

**Comment by marco-theraforge** [comment]
Thanks for catching this issue, @sakibk. As we discussed during our call, we are currently working on a new release with a fix.

**Comment by marco-theraforge** [comment]
@sakib, for the time being please make these changes with the version numbers:

  pod 'OTFToolBox', '1.0.1-alpha'
  pod 'OTFCloudantStore/CloudantCareHealth', '1.0.1-alpha'
  pod 'OTFCareKit/CareHealth', '2.0.2-alpha.1'
  pod 'OTFResearchKit', '2.0.0-alpha.1'

The new release will have an optimized set of dependencies and address this issue too.

Thanks and sorry for the inconvenience!

**Comment by sakibk** [comment]
Thank you @marco-theraforge, this definetly helps!
